export const robots = [
  {
    id: 1,
    name: "  Mahabalipuram ",
    username: "Bret",
    city: "Tamilnadu",
  },
  {
    id: 2,
    name: "Taj Mahal",
    username: "Antonette",
    city: "Uttar Pradesh",
  },
  {
    id: 3,
    name: "Varkala",
    username: "Samantha",
    city: "Kerala",
  },
  {
    id: 4,
    name: "Leh",
    username: "Karianne",
    city: "Ladakh",
  },
  {
    id: 5,
    name: "Alappey",
    username: "Kamren",
    city: "Kerala",
  },
  {
    id: 6,
    name: "Ajanta-caves",
    username: "Leopoldo_Corkery",
    city: "Maharashtra",
  },
  {
    id: 7,
    name: "Coorg",
    username: "Elwyn.Skiles",
    city: "Karnataka",
  },
  {
    id: 8,
    name: "Brihadeeswara Temple",
    username: "Maxime_Nienow",
    city: "Tamilnadu",
  },
  {
    id: 9,
    name: "Kaziranga National Park",
    username: "Delphine",
    city: "Assam",
  },
  {
    id: 10,
    name: "Wayanad",
    username: "Moriah.Stanton",
    city: "Kerala",
  },
  {
    id: 11,
    name: "Manali",
    username: "Moriah.Stanton",
    city: "Himachal Pradesh",
  },
  {
    id: 12,
    name: "Goa",
    username: "Moriah.Stanton",
    city: "Goa",
  },
  {
    id: 13,
    name: "Charminar",
    username: "Moriah.Stanton",
    city: "Hyderdabad",
  },
  {
    id: 14,
    name: "Qutb Minar",
    username: "Moriah.Stanton",
    city: "Delhi",
  },
  {
    id: 15,
    name: "Gwalior",
    username: "Moriah.Stanton",
    city: "Madhya Pradesh",
  },
  {
    id: 16,
    name: "Andaman Islands",
    username: "Moriah.Stanton",
    city: "Andaman and Nicobar",
  },
  {
    id: 17,
    name: "Shivanasamudra Falls",
    username: "Moriah.Stanton",
    city: "Karnataka",
  },
  {
    id: 18,
    name: "Kedarnath",
    username: "Moriah.Stanton",
    city: "Uttarakhand",
  },
  {
    id: 19,
    name: "Srisailam",
    username: "Moriah.Stanton",
    city: "Andhra Pradesh",
  },
  {
    id: 20,
    name: "Wonderla Amusement Park",
    username: "Moriah.Stanton",
    city: "Bangalore, Kerala",
  },
  {
    id: 21,
    name: "Kanyakumari – Southernmost Tip",
    username: "Moriah.Stanton",
    city: "Tamilnadu",
  },
  {
    id: 22,
    name: "Mysore",
    username: "Moriah.Stanton",
    city: "Karnataka",
  },
  {
    id: 23,
    name: "Nainital",
    username: "Moriah.Stanton",
    city: " Uttarakhand",
  },
  {
    id: 24,
    name: " Gorichen Peak",
    username: "Moriah.Stanton",
    city: "Arunachal Pradesh",
  },
  {
    id: 25,
    name: " Lakshadweep Islands",
    username: "Moriah.Stanton",
    city: "Lakshadweep",
  },
];
